services:
  - type: web
    name: breathe-esg-backend
    env: python
    buildCommand: "pip install -r requirements.txt && python manage.py migrate && python manage.py shell -c \"from ingestion.views import SetupViewSet; from django.http import HttpRequest; SetupViewSet().seed_data(HttpRequest())\""
    startCommand: "gunicorn config.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.2
      - key: CORS_ALLOW_ALL_ORIGINS
        value: True
      - key: DATABASE_URL
        fromDatabase:
          name: breathe-esg-db
          property: connectionString

  - type: web
    name: breathe-esg-frontend
    env: static
    buildCommand: "cd frontend && npm install && npm run build"
    staticPublishPath: "./frontend/dist"
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: VITE_API_URL
        value: https://breathe-esg-backend.onrender.com

databases:
  - name: breathe-esg-db
    databaseName: breathe_esg
    user: breathe_user
